# setup.ps1 — Unified installer/updater for ResolveLink
# Detects if already installed and runs appropriate action.
param(
    [switch]$Force,
    [switch]$NoBrowser
)

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent

# --- Detect install state ---
$installed = Test-Path "$root\.server.pid" -ErrorAction SilentlyContinue
$hasEnv = Test-Path "$root\.env" -ErrorAction SilentlyContinue
$hasNodeModules = Test-Path "$root\node_modules" -ErrorAction SilentlyContinue
$hasFrontend = Test-Path "$root\src\node_modules" -ErrorAction SilentlyContinue
$hasDist = Test-Path "$root\src\dist\index.html" -ErrorAction SilentlyContinue

if ($installed -and -not $Force) {
    Write-Host "ResolveLink is already installed." -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  Detected:" -ForegroundColor Yellow
    if ($hasEnv)        { Write-Host "    .env config      OK" -ForegroundColor Green }
    if ($hasNodeModules) { Write-Host "    node_modules     OK" -ForegroundColor Green }
    if ($hasFrontend)   { Write-Host "    frontend deps    OK" -ForegroundColor Green }
    if ($hasDist)       { Write-Host "    frontend build   OK" -ForegroundColor Green }
    Write-Host ""
    Write-Host "  Choose an action:" -ForegroundColor Yellow
    Write-Host "    [U] Update  — reinstall deps, rebuild, redeploy, restart" -ForegroundColor DarkGray
    Write-Host "    [C] Clear   — clear exports and/or temp directories" -ForegroundColor DarkGray
    Write-Host "    [R] Restart — restart the server" -ForegroundColor DarkGray
    Write-Host "    [S] Status  — check all components" -ForegroundColor DarkGray
    Write-Host "    [F] Force   — full reinstall from scratch" -ForegroundColor DarkGray
    Write-Host "    [Q] Quit" -ForegroundColor DarkGray
    Write-Host ""

    $choice = Read-Host "  Action"
    switch ($choice.ToUpper()) {
        "U" { & "$PSScriptRoot\setup.ps1" -Force; return }
        "C" { & "$PSScriptRoot\scripts\clear.ps1"; return }
        "R" { & "$PSScriptRoot\scripts\start.ps1"; return }
        "S" { & "$PSScriptRoot\scripts\status.ps1"; return }
        "F" { Write-Host "`n  Proceeding with full install..." -ForegroundColor Yellow }
        default { return }
    }
}

Write-Host ""
Write-Host "ResolveLink Setup" -ForegroundColor Cyan
Write-Host "================" -ForegroundColor Cyan

# --- Step 1: Install server dependencies ---
Write-Host "`n[1/7] Installing server dependencies..." -ForegroundColor Yellow
Push-Location "$root"
npm install
Pop-Location

# --- Step 2: Install + build frontend ---
Write-Host "`n[2/7] Building frontend..." -ForegroundColor Yellow
Push-Location "$root\src"
npm install
npm run build
Pop-Location

# --- Step 3: Deploy CEP extension ---
Write-Host "`n[3/7] Deploying AE extension..." -ForegroundColor Yellow
& "$PSScriptRoot\scripts\deploy-extension.ps1" -Quiet

# --- Step 4: Deploy Resolve script ---
Write-Host "`n[4/7] Deploying Resolve script..." -ForegroundColor Yellow
& "$PSScriptRoot\scripts\deploy-resolve-script.ps1" -Quiet

# --- Step 5: Ensure directories ---
New-Item -ItemType Directory -Force -Path "$root\exports" | Out-Null
New-Item -ItemType Directory -Force -Path "$root\temp" | Out-Null

# --- Step 6: Configure .env ---
if (-not $hasEnv -or $Force) {
    Write-Host "`n[5/7] Configuring paths..." -ForegroundColor Yellow
    Write-Host ""

    # Detect Python
    $pythonPath = ""
    foreach ($cmd in @("python", "python3", "py -3")) {
        try {
            $base = $cmd.Split(' ')[0]
            $ver = & cmd /c "$base --version 2>&1"
            if ($ver -match "Python 3\.(\d+)") {
                $minor = [int]$Matches[1]
                if ($minor -ge 10) {
                    $pythonPath = & cmd /c "where $base 2>nul" | Select-Object -First 1
                    Write-Host "  Found Python: $pythonPath ($ver)" -ForegroundColor Green
                    break
                }
            }
        } catch {}
    }

    # Detect AE
    $aePath = ""
    if (Test-Path "C:\Program Files\Adobe") {
        $aeDirs = Get-ChildItem "C:\Program Files\Adobe" -Directory |
            Where-Object { $_.Name -like "Adobe After Effects*" } |
            Sort-Object Name
        if ($aeDirs.Count -gt 0) {
            $aePath = Join-Path $aeDirs[-1].FullName "Support Files"
            Write-Host "  Found After Effects: $($aeDirs[-1].Name)" -ForegroundColor Green
        }
    }

    Write-Host ""
    $port = Read-Host "  Server port [3030]"
    if (-not $port) { $port = "3030" }

    $exportDir = Read-Host "  Export directory [./exports]"
    if (-not $exportDir) { $exportDir = "./exports" }

    $extraWatch = Read-Host "  Extra watch folders (comma-separated, or empty)"

    $envLines = @(
        "# ResolveLink Configuration (auto-generated by setup.ps1)"
        "PORT=$port"
        "HOST=127.0.0.1"
        "EXPORT_DIR=$exportDir"
        "TEMP_DIR=./temp"
        ""
    )
    if ($pythonPath) { $envLines += "PYTHON_PATH=$pythonPath" }
    if ($aePath)     { $envLines += "AE_PATH_WIN=$aePath" }
    if ($extraWatch) { $envLines += "WATCH_FOLDERS=$extraWatch" }
    $envLines += ""

    Set-Content -Path "$root\.env" -Value ($envLines -join "`n")
    Write-Host "`n  .env created!" -ForegroundColor Green
} else {
    Write-Host "`n[5/7] .env exists, skipping." -ForegroundColor DarkGray
}

# --- Step 7: Start server ---
Write-Host "`n[6/7] Starting server..." -ForegroundColor Yellow
& "$PSScriptRoot\scripts\start.ps1" -NoBrowser

# --- Done ---
Write-Host "`n[7/7] Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  ResolveLink is running at http://localhost:3030" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Commands:" -ForegroundColor DarkGray
Write-Host "    .\scripts\setup.ps1         — Reinstall / update" -ForegroundColor DarkGray
Write-Host "    .\scripts\start.ps1         — Start server" -ForegroundColor DarkGray
Write-Host "    .\scripts\stop.ps1          — Stop server" -ForegroundColor DarkGray
Write-Host "    .\scripts\status.ps1        — Check component status" -ForegroundColor DarkGray
Write-Host "    .\scripts\clear.ps1         — Clear exports/temp" -ForegroundColor DarkGray
Write-Host "    .\scripts\deploy-*          — Deploy extensions only" -ForegroundColor DarkGray

if (-not $NoBrowser) {
    Start-Process "http://localhost:3030"
}
