#!/bin/bash
# setup.sh — Unified installer/updater for ResolveLink (macOS/Linux)
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"

# --- Detect install state ---
installed=false
has_env=false
has_node=false
has_dist=false

[ -f "$ROOT/.server.pid" ] && [ -d "/proc/$(cat "$ROOT/.server.pid" 2>/dev/null)" ] 2>/dev/null && installed=true
[ -f "$ROOT/.env" ] && has_env=true
[ -d "$ROOT/node_modules" ] && has_node=true
[ -f "$ROOT/src/dist/index.html" ] && has_dist=true

if $installed && [ "$1" != "--force" ]; then
    echo ""
    echo "  ResolveLink is already installed."
    echo ""
    $has_env  && echo "    .env config      OK" || true
    $has_node && echo "    node_modules     OK" || true
    $has_dist && echo "    frontend build   OK" || true
    echo ""
    echo "  Usage: ./setup.sh [--force]"
    echo "    --force   Full reinstall from scratch"
    exit 0
fi

echo ""
echo "  ResolveLink Setup"
echo "  ================="
echo ""

# --- Step 1: Install server dependencies ---
echo "  [1/6] Installing server dependencies..."
cd "$ROOT"
npm install

# --- Step 2: Install + build frontend ---
echo "  [2/6] Building frontend..."
cd "$ROOT/src"
npm install
npm run build

# --- Step 3: Deploy Resolve script ---
echo "  [3/6] Deploying Resolve script..."
RESOLVE_SCRIPTS_DIR=""
if [[ "$OSTYPE" == "darwin"* ]]; then
    RESOLVE_SCRIPTS_DIR="$HOME/Library/Application Support/Blackmagic Design/DaVinci Resolve/Support/Fusion/Scripts/Utility"
else
    RESOLVE_SCRIPTS_DIR="$HOME/.local/share/DaVinci Resolve/Support/Fusion/Scripts/Utility"
fi
mkdir -p "$RESOLVE_SCRIPTS_DIR"
cp "$ROOT/resolve-scripts/send-to-ae.py" "$RESOLVE_SCRIPTS_DIR/send-to-ae.py"
echo "    Deployed -> $RESOLVE_SCRIPTS_DIR/send-to-ae.py"

# --- Step 4: Ensure directories ---
mkdir -p "$ROOT/exports"
mkdir -p "$ROOT/temp"

# --- Step 5: Configure .env ---
if ! $has_env || [ "$1" == "--force" ]; then
    echo "  [4/6] Configuring paths..."
    echo ""

    # Detect Python
    PYTHON_PATH=""
    for cmd in python3 python; do
        if command -v "$cmd" &> /dev/null; then
            ver=$("$cmd" --version 2>&1 | grep -oE '3\.[0-9]+')
            minor=$(echo "$ver" | cut -d. -f2)
            if [ "$minor" -ge 10 ] 2>/dev/null; then
                PYTHON_PATH="$(which "$cmd")"
                echo "    Found Python: $PYTHON_PATH ($ver)"
                break
            fi
        fi
    done

    # Detect AE (macOS only)
    AE_PATH=""
    if [[ "$OSTYPE" == "darwin"* ]]; then
        AE_DIR="/Applications"
        for app in "$AE_DIR"/Adobe\ After\ Effects*; do
            if [ -d "$app" ]; then
                if [ -f "$app/Contents/MacOS/AfterFX" ]; then
                    AE_PATH="$app"
                    echo "    Found After Effects: $(basename "$app")"
                    break
                fi
            fi
        done
    fi

    echo ""
    read -rp "    Server port [3030] " port
    port=${port:-3030}

    read -rp "    Export directory [./exports] " export_dir
    export_dir=${export_dir:-"./exports"}

    read -rp "    Extra watch folders (comma-separated, or empty) " extra_watch

    {
        echo "# ResolveLink Configuration (auto-generated by setup.sh)"
        echo "PORT=$port"
        echo "HOST=127.0.0.1"
        echo "EXPORT_DIR=$export_dir"
        echo "TEMP_DIR=./temp"
        echo ""
        [ -n "$PYTHON_PATH" ] && echo "PYTHON_PATH=$PYTHON_PATH"
        [ -n "$AE_PATH" ] && echo "AE_PATH_MAC=$AE_PATH"
        [ -n "$extra_watch" ] && echo "WATCH_FOLDERS=$extra_watch"
        echo ""
    } > "$ROOT/.env"
    echo ""
    echo "    .env created!"
else
    echo "  [4/6] .env exists, skipping."
fi

# --- Step 6: Start server ---
echo "  [5/6] Starting server..."
cd "$ROOT"
if [ -f ".server.pid" ]; then
    kill "$(cat .server.pid)" 2>/dev/null || true
    rm -f .server.pid
fi
nohup node server/index.js > /dev/null 2>&1 &
echo $! > .server.pid
echo "    Server PID: $(cat .server.pid)"

sleep 2

if curl -sf http://localhost:3030/api/health > /dev/null 2>&1; then
    echo "    Server running - http://localhost:3030"
else
    echo "    Server may still be starting, try http://localhost:3030"
fi

echo ""
echo "  [6/6] Setup complete!"
echo ""
echo "    ResolveLink is running at http://localhost:3030"
echo ""
echo "    Commands:"
echo "      ./scripts/setup.sh          — Reinstall / update"
echo "      ./scripts/start.sh          — Start server"
echo "      ./scripts/stop.sh           — Stop server"
echo "      ./scripts/status.sh         — Check component status"
